### ISSUE TITLE
Feedback del ejercicio de evaluación intermedia del sprint 2

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/dorcar-s2-evaluacion-intermedia-andreinavargas#1]
El html está hecho con prisa y el js no acaba de funcionar. Te recomiendo revisar definición y ejecución de funciones, e intentar seguir el guión propuesto para conseguir el ejercicio, cómo lo ves?

```
// Guardar la referencia a todos los elementos del DOM que vamos a usar en variables

// Generar el número aleatorio
// Y guardarlo en una variable

// Inicializar a 0 una variable de contador

// Crear una función que se ejecute cuando haga click en el botón de prueba
//  Esta función tiene que hacer:
//  1 - incrementar el contador
//  2 - y pintar el contador en mi html

//  3 - recoger el valor del campo
//  4 - Compararlo con mi número aleatorio
//    - Si son iguales -> pintar el mensaje de "Ganadora"
//    - Si es menor -> pintar el mensaje de "te has quedado corta"
//    - Si es mayor -> pintar el mensaje de "te has pasado"

// Asignar un listener al botón de prueba para que ejecute una función al hacer click
```

![You got this](https://media.giphy.com/media/rIzU0WhNSCX3a/giphy.gif)

**Comment by andreinavargas** [comment]
Hola Carlos, he seguido tus recomendaciones, una vez declaradas todas las variables, todo fluye muy fácil, no he mirado tu solución de clases, así que no se si es la mejor manera de hacerlo. Pero esta vez lo he conseguido.

En clases me he puesto nerviosa, no sabia por donde comenzar y el tiempo me ha jugado una mala pasada. Creo que siguiendo estos pasos, los proximos ejercicios seran mas faciles de abordar. 

https://github.com/Adalab/dorcar-s2-evaluacion-intermedia-andreinavargas/commit/b0ef22bbb5083805e1ac3063e25b65f396a58422

**Comment by oneeyedman** [comment]
Muy buen trabajo!
